### ISSUE TITLE
导入不进去啊

### ISSUE THREAD

**Issue by codeoffice** [DingJunyao/myenigma#1]
我是下载了的（python版本也是3.10.4的），但是我用import myenigma时出现找不到的问题。

**Comment by DingJunyao** [comment]
我自己测试了一下，是没有问题的。

<img width="734" alt="image" src="https://user-images.githubusercontent.com/11372753/182032682-7da844f3-b092-43b3-b530-351c7b44a650.png">

3.10 的小版本应该不会有太大的差异。

如果确实有问题，请给出详细的情况说明。

**Comment by DingJunyao** [comment]
由于长期未反馈，此议题关闭。
