### ISSUE TITLE
对于中文的支持

### ISSUE THREAD

**Issue by jefferycwb** [DingJunyao/myenigma#2]
我提一个建议，是不是可以利用unicode等编码规则在现有的enigma机制上再套一个壳子，这样对于中文的字符也能加密解密处理？

**Comment by DingJunyao** [comment]
编码规则不只一种，为增加可自定义性，我并不建议将其集成在该模块中。

以传统的 Emigma 为例，建议先通过某种方式处理中文，变为不区分大小写的拉丁字母序列，之后调用 myenigma 模块对其处理。解密同理。

模块也可以使用其他不重复的字符构建映射部分，不过如果直接使用汉字的话，可能有一点占时间、空间；并且映射规则需要自己定义。
